version: "3.4"

services:
  db:
    container_name: dev-postgres
    image: postgres
    volumes:
      - ./dev-data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
